version: '3.9'

services:
  generator:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    env_file:
      - stack.env 
    networks:
      - www_proxy
    volumes:
      - database:/app/data

  
networks:
  www_proxy:
    external: true
volumes:
  database: